name: xmlschema

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:

    runs-on:  ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14", "3.15.0-alpha.3", "pypy-3.10"]
        exclude:
          - os: macos-latest
            python-version: "3.10"
          - os: windows-latest
            python-version: "3.10"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pip and setuptools
        run: |
          python -m pip install --upgrade pip
          pip install setuptools
      - name: Build and install lxml for Python 3.15-alpha
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version == '3.15.0-alpha.3' }}
        run: |
          sudo apt-get install -y libxml2-dev libxslt-dev python3-dev
          pip install lxml
      - name: Install lxml for Python < 3.15
        if: ${{ matrix.python-version != '3.15.0-alpha.3' }}
        run: pip install lxml
      - name: Install other optional dependencies
        run: pip install jinja2
      - name: Test with unittest
        run: |
          pip install .
          python -m unittest
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 xmlschema --max-line-length=100 --statistics
      - name: Lint with mypy==1.18.2
        if: ${{ matrix.python-version == '3.15.0-alpha.3' || matrix.python-version == 'pypy-3.10' }}
        run: |
          pip install mypy==1.18.2 elementpath==5.1.0 lxml-stubs
          mypy --show-error-codes --strict xmlschema
      - name: Lint with mypy==1.19.1
        if: ${{ matrix.python-version != '3.15.0-alpha.3' && matrix.python-version != 'pypy-3.10' }}
        run: |
          pip install mypy==1.18.2 elementpath==5.1.0 lxml-stubs
          mypy --show-error-codes --strict xmlschema
